### ISSUE TITLE
w2v_feature_extract function question

### ISSUE THREAD

**Issue by xxp17457741** [chunyuanY/RumorDetection#2]
In preprocessing.py doc, there is a w2v_feature_extract function, it needs three inputs. What is twitter_w2v.bin? Or it is nothing??

**Comment by chunyuanY** [comment]
If you want to reproduce the experimental results, you can directly run the script: python run.py. We will release the tweet_w2v.bin and weibo_w2v.bin soon.

**Comment by chunyuanY** [comment]
> In preprocessing.py doc, there is a w2v_feature_extract function, it needs three inputs. What is twitter_w2v.bin? Or it is nothing??

If you want to reproduce the experimental results, you can directly run the script: python run.py. We have released the tweet_w2v.bin and weibo_w2v.bin at here: https://drive.google.com/drive/folders/1IMOJCyolpYtoflEqQsj3jn5BYnaRhsiY?usp=sharing.
