### ISSUE TITLE
how to get the weight of user 

### ISSUE THREAD

**Issue by smallhaes** [chunyuanY/RumorDetection#3]
randomly initialize or preceed with certain algorithm
thanks~

**Comment by chunyuanY** [comment]
Hello. The user embedding is randomly initialized. If you have any other questions, please don't hesitate to email me.

**Comment by chunyuanY** [comment]
> randomly initialize or preceed with certain algorithm
> thanks~

Hello. The user embedding is randomly initialized. If you have any other questions, please don't hesitate to email me.

**Comment by smallhaes** [comment]
@chunyuanY wow! thanks a lot~ 😄
