### ISSUE TITLE
edge between users or edge between tweets

### ISSUE THREAD

**Issue by smallhaes** [chunyuanY/RumorDetection#4]
hi~ chunyuan, the paper says, "we connect the user nodes if they participate in common microblogs and link the nodes of source tweets by their common users", when i check weibo dataset, the file 'weibo_graph.txt' does not contain links between two uses or two source tweets. it only contains 4664 records between tweet and users. so does twitter15_graph.txt and twitter16_graph.txt
so, could GLAN still works without links between two uses or two source tweets ?

**Comment by chunyuanY** [comment]
> hi~ chunyuan, the paper says, "we connect the user nodes if they participate in common microblogs and link the nodes of source tweets by their common users", when i check weibo dataset, the file 'weibo_graph.txt' does not contain links between two uses or two source tweets. it only contains 4664 records between tweet and users. so does twitter15_graph.txt and twitter16_graph.txt
> so, could GLAN still works without links between two uses or two source tweets ?

Hello. In the original dataset, there is no direct link between two users, so the relation between users is implicitly contained in user1-tweet-user2, the model can learn this kind of relation and obtain the similarity of users.

**Comment by smallhaes** [comment]
got it! thanks for your explanation again~ 😄 😄
