### ISSUE TITLE
请问您的数据中包含回复吗

### ISSUE THREAD

**Issue by xianjueliu** [chunyuanY/RumorDetection#5]
看了一下您的论文，是有用到回复的，但是提供的数据和代码里似乎没有回复内容，，JingMa的推特回复好像只开源了tf-idf处理后的内容。
请问是我哪里理解错了吗？不知道问题是否描述清楚了，望解答，感谢

**Comment by chunyuanY** [comment]
> 看了一下您的论文，是有用到回复的，但是提供的数据和代码里似乎没有回复内容，JingMa的推特回复好像只开源了tf-idf处理后的内容。
> 请问是我哪里理解错了吗？不知道问题是否描述清楚了，望解答，感谢

你好，只用到了回复关系，没有用到回复的文本。Jing Ma提供的数据中没有包含回复的文本。

**Comment by xianjueliu** [comment]
> > 看了一下您的论文，是有用到回复的，但是提供的数据和代码里似乎没有回复内容，JingMa的推特回复好像只开源了tf-idf处理后的内容。
> > 请问是我哪里理解错了吗？不知道问题是否描述清楚了，望解答，感谢
> 
> 你好，只用到了回复关系，没有用到回复的文本。Jing Ma提供的数据中没有包含回复的文本。

感谢回复，谢谢！
